integer1 = raw_input('Enter an integer: ')
integer2 = raw_input('Enter another: ')
print integer1, ' + ', integer2, ' = ', int(integer1) + int(integer2)
print integer1, ' - ', integer2, ' = ', int(integer1) - int(integer2)
print integer1, ' * ', integer2, ' = ', int(integer1) * int(integer2)
print integer1, ' / ', integer2, ' = ', int(integer1) / int(integer2)
print integer1, ' % ', integer2, ' = ', int(integer1) % int(integer2)
